export type Severity = 'critical'|'high'|'medium'|'low'|'info';
export type ChangeKind = 'nodeAdded'|'nodeRemoved'|'nodeReplaced'|'nodeMoved'|'nodeRenamed'|'fieldChanged'|'fieldBelowTolerance'|'childOrderChanged'|'transformChanged'|'geometryChanged'|'appearanceChanged'|'materialChanged'|'textureReferenceChanged'|'defUseChanged'|'routeAdded'|'routeRemoved'|'routeRewired'|'animationConfigChanged'|'timeConfigChanged'|'interactionChanged'|'viewpointChanged'|'lightChanged'|'metadataChanged'|'documentContextChanged'|'unsupportedFeature'|'invalidReference'|'matchUncertain';
export interface ToleranceConfig { floatAbs: number; floatRel: number; vectorAbs: number; rotationRadians: number; colorAbs: number }
export interface SourceLocation { line?: number; column?: number; elementPath: string }
export interface NodeRef { nodeType: string; defName?: string; scopePath: string; path: string; source?: SourceLocation }
export interface ValueSnapshot { fieldType?: string; value: unknown; lexicalValue?: string }
export interface Diagnostic { code: string; severity: 'warning'|'error'; side?: 'before'|'after'; message: string; path?: string; source?: SourceLocation }
export interface ChangeRecord { id: string; kind: ChangeKind; severity: Severity; confidence: 'high'|'medium'|'low'; category: string; message: string; before?: ValueSnapshot; after?: ValueSnapshot; beforePath?: string; afterPath?: string; beforeNode?: NodeRef; afterNode?: NodeRef; field?: string; toleranceApplied?: number; affectedUseCount?: number; relatedChangeIds?: string[]; unsupportedReason?: string; movedPoints?: number; totalPoints?: number }
export interface InputSummary { name?: string; byteLength: number; sha256?: string; x3dVersion?: string; profile?: string; components: Array<{name:string;level:number}>; parsedNodeCount: number }
export interface X3DiffReport { schemaVersion: '1.0'; toolVersion: string; inputs: {before:InputSummary;after:InputSummary}; config: ToleranceConfig & {enabledCategories:string[]}; summary: {status:'complete'|'completeWithWarnings'|'incomplete'|'failed';countsByKind:Record<string,number>;countsBySeverity:Record<Severity,number>;unsupportedCount:number}; changes: ChangeRecord[]; diagnostics: Diagnostic[]; catalog: {version:'3.3'; modelSha256:string; schemaSha256:string; supportedNodes:string[]; supportedFieldTypes:string[]} }
